apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  namespace: hospital-system
  labels:
    app: hospital-management

data:
  DB_NAME: "${MYSQL_DATABASE}"
  DB_USER: "${MYSQL_USER}"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "3306"
  FRONTEND_URL: "http://localhost"

