apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hospital-system
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0        # zero-downtime: new pod ready before old is killed
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret   # required to pull from Docker Hub private registry
      containers:
        - name: backend
          image: hospital-pms-backend:latest   # replaced by sed in deploy.yml CI step
          imagePullPolicy: Always              # always pull latest from Docker Hub
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: hospital-config
            - secretRef:
                name: hospital-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30   # give backend time to connect to RDS on startup
            periodSeconds: 10
            failureThreshold: 6       # 60s total grace period before pod marked Unready
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hospital-system
  labels:
    app: backend
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: backend
