apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital-system
  labels:
    app: hospital-management
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET: "${ACCESS_TOKEN_SECRET}"
  REFRESH_TOKEN_SECRET: "${REFRESH_TOKEN_SECRET}"
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
